spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buzzwrite
    username: root
    password: Coldwind123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
