
export const EDIT_USER="EDIT_USER";
export const GET_USER_BY_USERNAME="GET_USER_BY_USERNAME";
export const GET_USER_BY_TOKEN="GET_USER_BY_TOKEN";
export const SEARCH_AUTHORS="SEARCH_AUTHORS";
export const GET_ALL_AUTHORS="GET_ALL_AUTHORS";
export const GET_USER_BY_ID="GET_USER_BY_ID";
export const GET_USER_BY_EMAIL="GET_USER_BY_EMAIL";